name: Build Algoh Support Full Matrix (Manual)

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        description: 'Upload build artifacts'
        type: boolean
        default: true

jobs:
  build-algoh-support:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: ${{ inputs.upload-artifact == true }}
      upload-tag: "2.0.0"
